[measurements]
mr_seam = "ENTER_MRSEAM_HERE"
mrsigner_seam = "ENTER_MRSIGNERSEAM_HERE"
mr_td = "ENTER_MRTD_HERE"

mr_config_id = "none"
mr_owner = "none"
mr_owner_config = "none"

rtmr0 = "ENTER_RTMR0_HERE"
rtmr1 = "ENTER_RTMR1_HERE"
rtmr2 = "ENTER_RTMR2_HERE"
rtmr3 = "ENTER_RTMR3_HERE"

[policy]
allow_debug = false
allow_collateral_expiration = true
allow_configuration_needed = false
allow_sw_hardening_needed = false
allow_out_of_date = false
allow_td_relaunch_advised = true
allow_smt_enabled = true
required_tcb_eval_ds_num = 0
allowed_sa_list = []